version: "3.9"

services:
  valheim:
    image: ghcr.io/YOUR_GH_USER/valheim-from-scratch:latest
    container_name: valheim
    stop_grace_period: 120s
    ports:
      - "${SERVER_PORT}-${SERVER_PORT+2}:${SERVER_PORT}-${SERVER_PORT+2}/udp"
    environment:
      TZ: ${TZ}
      SERVER_NAME: ${SERVER_NAME}
      WORLD_NAME: ${WORLD_NAME}
      SERVER_PASS: ${SERVER_PASS}
      SERVER_PUBLIC: ${SERVER_PUBLIC}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      # All persistent files live here (Windows-friendly path example):
      - "C:/Valheim:/config"
    restart: unless-stopped
