version: "3.8"

services:
  valheim:
    build: .
    container_name: valheim
    cap_add:
      - sys_nice
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - "C:/ValheimServer:/config"
      - "C:/ValheimServer/data:/home/steam/valheim"
    environment:
      - SERVER_NAME=Eldradia Reborn
      - WORLD_NAME=Eldradia
      - SERVER_PASS=xdxdx
      - SERVER_PUBLIC=0
      - TZ=America/New_York
    restart: unless-stopped
