version: "3.9"

services:
  valheim:
    image: ghcr.io/chubbs1900/eldradia-valheim-dedicated-server:latest
    container_name: valheim
    stop_grace_period: 120s
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      TZ: America/New_York
      SERVER_NAME: Eldradia Reborn
      WORLD_NAME: Eldradia
      SERVER_PASS: change-me
      SERVER_PUBLIC: "0"    # 1 = public
      SERVER_PORT: "2456"
    volumes:
      - "C:/Valheim:/config"   # change to P:/Valheim if you prefer
    restart: unless-stopped
